apiVersion: apps/v1
kind: Deployment
metadata:
    name: 2048-app
    labels:
        app: "2048"
spec:
    replicas: 2
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    selector:
        matchLabels:
            app: "2048"
    template:
        metadata:
            labels:
                app: "2048"
        spec:
            containers:
            - name: "2048-game"
              image: ghcr.io/uyarburak/2048:v0.1.0
              ports:
                - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name:  "game-2048"
spec:
  selector:
    app:  "2048"
  type:  LoadBalancer 
  ports:
  - name:  http
    port:  80
    targetPort:  80
